function Hd = BDSsimfilter_4M
%BDSSIMFILTER_4M Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 29-May-2018 11:21:03
% GroupDelay = 59
% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

Fstop1 = 0.0594;           % First Stopband Frequency
Fpass1 = 0.1094;           % First Passband Frequency
Fpass2 = 0.8906;           % Second Passband Frequency
Fstop2 = 0.9406;           % Second Stopband Frequency
Dstop1 = 0.0031622776602;  % First Stopband Attenuation
Dpass  = 0.057501127785;   % Passband Ripple
Dstop2 = 0.0031622776602;  % Second Stopband Attenuation
flag   = 'scale';          % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2], [0 1 0], ...
    [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
% Hd = dsp.FIRFilter( ...
%     'Numerator', b);
Hd = dfilt.dffir(b);
% [EOF]
